package com.tts.blog.BlogPost;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class BlogPost {
    //sets ID as primary key
    @Id
    //allows the Id to be generated by the underlying database
    @GeneratedValue(strategy = GenerationType.AUTO) 
    private Long id;
    private String title;
    private String author;

    @Column(length = 1000)
    private String blogEntry;


    public BlogPost() {
        //non-argument constructor needed for JPA
    }
    

    public BlogPost(String title, String author, String blogEntry) {

        this.title = title;
        this.author = author;
        this.blogEntry = blogEntry;
    }


    public Long getId() {
        return this.id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getBlogEntry() {
        return this.blogEntry;
    }

    public void setBlogEntry(String blogEntry) {
        this.blogEntry = blogEntry;
    }


    @Override
    public String toString() {
        return "BlogPost [author=" + author + ", blogEntry=" + blogEntry + ", id=" + id + ", title=" + title + "]";
    }

    



















}